-- OBJECTS
local OBJECTS_PATH = (...)

require(OBJECTS_PATH..".aseprite")
require(OBJECTS_PATH..".sprite")
require(OBJECTS_PATH..".animation")
require(OBJECTS_PATH..".gameobject")
require(OBJECTS_PATH..".state")
require(OBJECTS_PATH..".camera")
require(OBJECTS_PATH..".entities.player")
require(OBJECTS_PATH..".tilemap.tileset")
require(OBJECTS_PATH..".tilemap.tile")
require(OBJECTS_PATH..".tilemap.level")
require(OBJECTS_PATH..".ui.mamonoro.timer")
require(OBJECTS_PATH..".mobile.touchcontrols")